### ISSUE TITLE
Task 1 Submissions

### ISSUE THREAD

**Issue by ak-garg** [opencodeiiita/CodeLines#2]
While making a PR for this Task , mention this issue number.

**Comment by Mridul20** [comment]
Sir I want to contribute on this project

**Comment by garvitchittora** [comment]
I want to work on this project

**Comment by amit2223** [comment]
sir i want to work on this

**Comment by Piyush4064** [comment]
Want to work on this

**Comment by anirudh2019** [comment]
want to work on this project

**Comment by naina24** [comment]
@opencodebot claim

**Comment by ABHIINAV12** [comment]
sir i want to contribute to this , how can i began

**Comment by Princeraaz** [comment]
sir I want to work on this project.

**Comment by Xenomorphing19** [comment]
sir i want to work on this

**Comment by harshthete001** [comment]
I want to work on this project

**Comment by Cipher-vasu** [comment]
sir i want to work on this project

**Comment by ankit4284** [comment]
@ak-garg Sir the original file has been changed by a PR, what to do now?

**Comment by blaze-assault** [comment]
sir made a pr
